import { integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

const audit = { createdAt: text("created_at").notNull().default("CURRENT_TIMESTAMP"), updatedAt: text("updated_at").notNull().default("CURRENT_TIMESTAMP") };

export const legalEntities = sqliteTable("legal_entities", { id: text("id").primaryKey(), legalName: text("legal_name").notNull(), tradingName: text("trading_name"), legalForm: text("legal_form").notNull(), kvk: text("kvk").notNull(), rsin: text("rsin"), ...audit });
export const appUsers = sqliteTable("app_users", { email: text("email").primaryKey(), displayName: text("display_name").notNull(), role: text("role").notNull(), active: integer("active", { mode: "boolean" }).notNull().default(true), ...audit });
export const sourceProviders = sqliteTable("source_providers", { id: text("id").primaryKey(), name: text("name").notNull(), category: text("category").notNull(), activeFrom: text("active_from"), activeTo: text("active_to"), status: text("status").notNull(), ...audit });
export const sourceFiles = sqliteTable("source_files", { id: text("id").primaryKey(), providerId: text("provider_id"), fileName: text("file_name").notNull(), drivePath: text("drive_path").notNull(), driveFileId: text("drive_file_id"), objectKey: text("object_key"), sha256: text("sha256").notNull(), mimeType: text("mime_type"), periodStart: text("period_start"), periodEnd: text("period_end"), receivedAt: text("received_at").notNull(), status: text("status").notNull(), ...audit });
export const ingestionRuns = sqliteTable("ingestion_runs", { id: text("id").primaryKey(), sourceFileId: text("source_file_id").notNull(), adapter: text("adapter").notNull(), adapterVersion: text("adapter_version").notNull(), rowsRead: integer("rows_read").notNull().default(0), rowsAccepted: integer("rows_accepted").notNull().default(0), rowsRejected: integer("rows_rejected").notNull().default(0), status: text("status").notNull(), startedAt: text("started_at").notNull(), completedAt: text("completed_at") });
export const marketplaceDaily = sqliteTable("marketplace_daily", { id: text("id").primaryKey(), sourceFileId: text("source_file_id").notNull(), salesDate: text("sales_date").notNull(), ean: text("ean").notNull(), revenue: real("revenue").notNull(), sales: integer("sales").notNull(), orders: integer("orders").notNull(), visits: integer("visits").notNull(), rowHash: text("row_hash").notNull(), ...audit });
export const bankStatements = sqliteTable("bank_statements", { id: text("id").primaryKey(), sourceFileId: text("source_file_id").notNull(), accountRef: text("account_ref").notNull(), periodStart: text("period_start").notNull(), periodEnd: text("period_end").notNull(), openingBalance: real("opening_balance").notNull(), credits: real("credits").notNull(), debits: real("debits").notNull(), closingBalance: real("closing_balance").notNull(), currency: text("currency").notNull().default("EUR"), ...audit });
export const bankTransactions = sqliteTable("bank_transactions", { id: text("id").primaryKey(), statementId: text("statement_id").notNull(), bookedAt: text("booked_at").notNull(), amount: real("amount").notNull(), description: text("description").notNull(), counterparty: text("counterparty"), transactionRef: text("transaction_ref"), ...audit });
export const settlements = sqliteTable("settlements", { id: text("id").primaryKey(), sourceFileId: text("source_file_id").notNull(), provider: text("provider").notNull(), grossAmount: real("gross_amount").notNull(), adjustmentAmount: real("adjustment_amount").notNull(), netAmount: real("net_amount").notNull(), currency: text("currency").notNull().default("EUR"), paidAt: text("paid_at"), matchedTransactionId: text("matched_transaction_id"), matchStatus: text("match_status").notNull(), ...audit });
export const reconciliationRuns = sqliteTable("reconciliation_runs", { id: text("id").primaryKey(), period: text("period").notNull(), ruleVersion: text("rule_version").notNull(), matchedCount: integer("matched_count").notNull(), unmatchedCount: integer("unmatched_count").notNull(), difference: real("difference").notNull(), status: text("status").notNull(), approvedBy: text("approved_by"), ...audit });
export const exceptions = sqliteTable("exceptions", { id: text("id").primaryKey(), title: text("title").notNull(), severity: text("severity").notNull(), status: text("status").notNull(), source: text("source").notNull(), detail: text("detail").notNull(), owner: text("owner").notNull(), resolution: text("resolution"), resolvedBy: text("resolved_by"), resolvedAt: text("resolved_at"), ...audit });
export const approvals = sqliteTable("approvals", { id: text("id").primaryKey(), subjectType: text("subject_type").notNull(), subjectId: text("subject_id").notNull(), decision: text("decision").notNull(), rationale: text("rationale"), actorEmail: text("actor_email").notNull(), decidedAt: text("decided_at").notNull() });
export const accountingPolicies = sqliteTable("accounting_policies", { id: text("id").primaryKey(), name: text("name").notNull(), version: integer("version").notNull(), definition: text("definition").notNull(), effectiveFrom: text("effective_from").notNull(), status: text("status").notNull(), approvedBy: text("approved_by"), ...audit });
export const auditEvents = sqliteTable("audit_events", { id: text("id").primaryKey(), actorEmail: text("actor_email").notNull(), action: text("action").notNull(), objectType: text("object_type").notNull(), objectId: text("object_id").notNull(), beforeJson: text("before_json"), afterJson: text("after_json"), occurredAt: text("occurred_at").notNull() });
